apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: slack
    receivers:
      - name: slack
        slack_configs:
          - send_resolved: true
            username: 'Prometheus Alertmanager'
            channel: '#devops-challenge'
            api_url: 'https://hooks.slack.com/services/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'