apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  custom.ini: |
    [server]
    http_addr = 0.0.0.0
    http_port = 3000

    [auth]
    disable_login_form = true

    [security]
    admin_user = admin
    admin_password = admin

    [analytics]
    check_for_updates = false